model = "ens:ecmwf_aifs025"
llm = "or:openai/gpt-5.1"
context_llm = "gpt-4o"
web_root = "./outputs/example-site"

location_forecast_days = 4
location_wordiness = "normal"
location_reasoning = "high"
location_impact_based = true
location_thin_select = 10

area_forecast_days = 2
area_wordiness = "normal"
area_reasoning = "high"
area_impact_based = true
area_thin_select = 10

snow_levels = false
enable_reasoning = true
recent_overwrite_minutes = 0

temperature_unit = "celsius"
precipitation_unit = "mm"
windspeed_unit = "kph"

[[location]]
name = "Otaki, New Zealand"
model = "ens:ecmwf_aifs025"
translation_language = "Maori"

[[location]]
name = "Seattle, Washington"
model = "ens:icon_seamless"

temperature_unit = "fahrenheit"
precipitation_unit = "in"
windspeed_unit = "mph"

[[location]]
name = "Bedford, Massachusetts"
model = "ens:ecmwf_ifs025"

temperature_unit = "fahrenheit"
precipitation_unit = "in"
windspeed_unit = "mph"

[[location]]
name = "Kingston, Jamaica"
translation_language = "jam"
model = "ens:icon_seamless"

windspeed_unit = "mph"
precipitation_unit = "inch"

[[area]]
name = "Trinidad and Tobago"
translation_language = "Trinidadian Creole English"
snow_levels = false
model = "ens:gem_global"
locations = [
  "Port of Spain, Trinidad and Tobago",
  "Arima, Trinidad and Tobago",
  "Toco, Trinidad and Tobago",
  "Manzanilla, Trinidad and Tobago",
  "Mayaro, Trinidad and Tobago",
  "San Fernando, Trinidad and Tobago",
  "Point Fortin, Trinidad and Tobago",
  "Cedros, Trinidad and Tobago",
  "Moruga, Trinidad and Tobago",
  "Crown Point, Trinidad and Tobago",
  "Roxborough, Trinidad and Tobago",
]
