model = "det:ecmwf_ifs"
"llm 5.1" = "or:openai/gpt-5.1"
llm = "or:google/gemini-3-flash-preview"
"llm free" = "or:nex-agi/deepseek-v3.1-nex-n1:free"
translation_llm = "or:openai/gpt-5-mini"
context_llm = "gemini-3-flash-preview"
enable_reasoning = true
snow_levels = true

location_forecast_days = 7
location_wordiness = "detailed"
location_reasoning = "high"
location_impact_based = true
location_thin_select = 10

area_forecast_days = 2
area_wordiness = "normal"
area_reasoning = "medium"
area_impact_based = true
area_thin_select = 10

temperature_unit = "celsius"
precipitation_unit = "mm"
windspeed_unit = "kph"

web_root = "./outputs/example-site/otaki"
recent_overwrite_minutes = 0

[[location]]
name = "Otaki Beach, New Zealand"

[[location]]
name = "Otaki Beach, New Zealand"
model = "ens:ecmwf_ifs025"

[[location]]
name = "Wanaka, New Zealand"

[[location]]
name = "Marchissy, Switzerland"
model = "det:icon_seamless"
